#! /bin/sh
#curl http://169.254.169.254/latest/meta-data/public-hostname
DAVS=$(curl -s http://169.254.169.254/latest/meta-data/public-hostname)
sed -i s/tcp:.*:/tcp:$DAVS:/g AOR1.xml
sed -i s/tcp:.*:/tcp:$DAVS:/g AOR2.xml
sed -i s/tcp:.*:/tcp:$DAVS:/g FOR.xml
mfds -g 5 $PWD/AOR1.xml
mfds -g 5 $PWD/AOR2.xml
mfds -g 5 $PWD/FOR.xml


